/**
 * Static national pokedex data (Gen I-IV, #1-493) used for the team slot picker.
 * Generated once from PokeAPI species names (English) and the veekun pokedex
 * dataset (German), kept static so the app works fully offline.
 *
 * Both the English (`name`) and German (`nameDe`) names are first-class,
 * static data here rather than component-local string hacks, so any UI that
 * needs to search/display Pokemon names in either language can share this
 * single source of truth.
 */

import type { TooltipLanguage } from './overlaySettings';

export interface PokedexEntry {
  id: number;
  name: string;
  nameDe: string;
}

export const POKEDEX: PokedexEntry[] = [
  { id: 1, name: "Bulbasaur", nameDe: "Bisasam" },
  { id: 2, name: "Ivysaur", nameDe: "Bisaknosp" },
  { id: 3, name: "Venusaur", nameDe: "Bisaflor" },
  { id: 4, name: "Charmander", nameDe: "Glumanda" },
  { id: 5, name: "Charmeleon", nameDe: "Glutexo" },
  { id: 6, name: "Charizard", nameDe: "Glurak" },
  { id: 7, name: "Squirtle", nameDe: "Schiggy" },
  { id: 8, name: "Wartortle", nameDe: "Schillok" },
  { id: 9, name: "Blastoise", nameDe: "Turtok" },
  { id: 10, name: "Caterpie", nameDe: "Raupy" },
  { id: 11, name: "Metapod", nameDe: "Safcon" },
  { id: 12, name: "Butterfree", nameDe: "Smettbo" },
  { id: 13, name: "Weedle", nameDe: "Hornliu" },
  { id: 14, name: "Kakuna", nameDe: "Kokuna" },
  { id: 15, name: "Beedrill", nameDe: "Bibor" },
  { id: 16, name: "Pidgey", nameDe: "Taubsi" },
  { id: 17, name: "Pidgeotto", nameDe: "Tauboga" },
  { id: 18, name: "Pidgeot", nameDe: "Tauboss" },
  { id: 19, name: "Rattata", nameDe: "Rattfratz" },
  { id: 20, name: "Raticate", nameDe: "Rattikarl" },
  { id: 21, name: "Spearow", nameDe: "Habitak" },
  { id: 22, name: "Fearow", nameDe: "Ibitak" },
  { id: 23, name: "Ekans", nameDe: "Rettan" },
  { id: 24, name: "Arbok", nameDe: "Arbok" },
  { id: 25, name: "Pikachu", nameDe: "Pikachu" },
  { id: 26, name: "Raichu", nameDe: "Raichu" },
  { id: 27, name: "Sandshrew", nameDe: "Sandan" },
  { id: 28, name: "Sandslash", nameDe: "Sandamer" },
  { id: 29, name: "Nidoran F", nameDe: "Nidoran♀" },
  { id: 30, name: "Nidorina", nameDe: "Nidorina" },
  { id: 31, name: "Nidoqueen", nameDe: "Nidoqueen" },
  { id: 32, name: "Nidoran M", nameDe: "Nidoran♂" },
  { id: 33, name: "Nidorino", nameDe: "Nidorino" },
  { id: 34, name: "Nidoking", nameDe: "Nidoking" },
  { id: 35, name: "Clefairy", nameDe: "Piepi" },
  { id: 36, name: "Clefable", nameDe: "Pixi" },
  { id: 37, name: "Vulpix", nameDe: "Vulpix" },
  { id: 38, name: "Ninetales", nameDe: "Vulnona" },
  { id: 39, name: "Jigglypuff", nameDe: "Pummeluff" },
  { id: 40, name: "Wigglytuff", nameDe: "Knuddeluff" },
  { id: 41, name: "Zubat", nameDe: "Zubat" },
  { id: 42, name: "Golbat", nameDe: "Golbat" },
  { id: 43, name: "Oddish", nameDe: "Myrapla" },
  { id: 44, name: "Gloom", nameDe: "Duflor" },
  { id: 45, name: "Vileplume", nameDe: "Giflor" },
  { id: 46, name: "Paras", nameDe: "Paras" },
  { id: 47, name: "Parasect", nameDe: "Parasek" },
  { id: 48, name: "Venonat", nameDe: "Bluzuk" },
  { id: 49, name: "Venomoth", nameDe: "Omot" },
  { id: 50, name: "Diglett", nameDe: "Digda" },
  { id: 51, name: "Dugtrio", nameDe: "Digdri" },
  { id: 52, name: "Meowth", nameDe: "Mauzi" },
  { id: 53, name: "Persian", nameDe: "Snobilikat" },
  { id: 54, name: "Psyduck", nameDe: "Enton" },
  { id: 55, name: "Golduck", nameDe: "Entoron" },
  { id: 56, name: "Mankey", nameDe: "Menki" },
  { id: 57, name: "Primeape", nameDe: "Rasaff" },
  { id: 58, name: "Growlithe", nameDe: "Fukano" },
  { id: 59, name: "Arcanine", nameDe: "Arkani" },
  { id: 60, name: "Poliwag", nameDe: "Quapsel" },
  { id: 61, name: "Poliwhirl", nameDe: "Quaputzi" },
  { id: 62, name: "Poliwrath", nameDe: "Quappo" },
  { id: 63, name: "Abra", nameDe: "Abra" },
  { id: 64, name: "Kadabra", nameDe: "Kadabra" },
  { id: 65, name: "Alakazam", nameDe: "Simsala" },
  { id: 66, name: "Machop", nameDe: "Machollo" },
  { id: 67, name: "Machoke", nameDe: "Maschock" },
  { id: 68, name: "Machamp", nameDe: "Machomei" },
  { id: 69, name: "Bellsprout", nameDe: "Knofensa" },
  { id: 70, name: "Weepinbell", nameDe: "Ultrigaria" },
  { id: 71, name: "Victreebel", nameDe: "Sarzenia" },
  { id: 72, name: "Tentacool", nameDe: "Tentacha" },
  { id: 73, name: "Tentacruel", nameDe: "Tentoxa" },
  { id: 74, name: "Geodude", nameDe: "Kleinstein" },
  { id: 75, name: "Graveler", nameDe: "Georok" },
  { id: 76, name: "Golem", nameDe: "Geowaz" },
  { id: 77, name: "Ponyta", nameDe: "Ponita" },
  { id: 78, name: "Rapidash", nameDe: "Gallopa" },
  { id: 79, name: "Slowpoke", nameDe: "Flegmon" },
  { id: 80, name: "Slowbro", nameDe: "Lahmus" },
  { id: 81, name: "Magnemite", nameDe: "Magnetilo" },
  { id: 82, name: "Magneton", nameDe: "Magneton" },
  { id: 83, name: "Farfetchd", nameDe: "Porenta" },
  { id: 84, name: "Doduo", nameDe: "Dodu" },
  { id: 85, name: "Dodrio", nameDe: "Dodri" },
  { id: 86, name: "Seel", nameDe: "Jurob" },
  { id: 87, name: "Dewgong", nameDe: "Jugong" },
  { id: 88, name: "Grimer", nameDe: "Sleima" },
  { id: 89, name: "Muk", nameDe: "Sleimok" },
  { id: 90, name: "Shellder", nameDe: "Muschas" },
  { id: 91, name: "Cloyster", nameDe: "Austos" },
  { id: 92, name: "Gastly", nameDe: "Nebulak" },
  { id: 93, name: "Haunter", nameDe: "Alpollo" },
  { id: 94, name: "Gengar", nameDe: "Gengar" },
  { id: 95, name: "Onix", nameDe: "Onix" },
  { id: 96, name: "Drowzee", nameDe: "Traumato" },
  { id: 97, name: "Hypno", nameDe: "Hypno" },
  { id: 98, name: "Krabby", nameDe: "Krabby" },
  { id: 99, name: "Kingler", nameDe: "Kingler" },
  { id: 100, name: "Voltorb", nameDe: "Voltobal" },
  { id: 101, name: "Electrode", nameDe: "Lektrobal" },
  { id: 102, name: "Exeggcute", nameDe: "Owei" },
  { id: 103, name: "Exeggutor", nameDe: "Kokowei" },
  { id: 104, name: "Cubone", nameDe: "Tragosso" },
  { id: 105, name: "Marowak", nameDe: "Knogga" },
  { id: 106, name: "Hitmonlee", nameDe: "Kicklee" },
  { id: 107, name: "Hitmonchan", nameDe: "Nockchan" },
  { id: 108, name: "Lickitung", nameDe: "Schlurp" },
  { id: 109, name: "Koffing", nameDe: "Smogon" },
  { id: 110, name: "Weezing", nameDe: "Smogmog" },
  { id: 111, name: "Rhyhorn", nameDe: "Rihorn" },
  { id: 112, name: "Rhydon", nameDe: "Rizeros" },
  { id: 113, name: "Chansey", nameDe: "Chaneira" },
  { id: 114, name: "Tangela", nameDe: "Tangela" },
  { id: 115, name: "Kangaskhan", nameDe: "Kangama" },
  { id: 116, name: "Horsea", nameDe: "Seeper" },
  { id: 117, name: "Seadra", nameDe: "Seemon" },
  { id: 118, name: "Goldeen", nameDe: "Goldini" },
  { id: 119, name: "Seaking", nameDe: "Golking" },
  { id: 120, name: "Staryu", nameDe: "Sterndu" },
  { id: 121, name: "Starmie", nameDe: "Starmie" },
  { id: 122, name: "Mr Mime", nameDe: "Pantimos" },
  { id: 123, name: "Scyther", nameDe: "Sichlor" },
  { id: 124, name: "Jynx", nameDe: "Rossana" },
  { id: 125, name: "Electabuzz", nameDe: "Elektek" },
  { id: 126, name: "Magmar", nameDe: "Magmar" },
  { id: 127, name: "Pinsir", nameDe: "Pinsir" },
  { id: 128, name: "Tauros", nameDe: "Tauros" },
  { id: 129, name: "Magikarp", nameDe: "Karpador" },
  { id: 130, name: "Gyarados", nameDe: "Garados" },
  { id: 131, name: "Lapras", nameDe: "Lapras" },
  { id: 132, name: "Ditto", nameDe: "Ditto" },
  { id: 133, name: "Eevee", nameDe: "Evoli" },
  { id: 134, name: "Vaporeon", nameDe: "Aquana" },
  { id: 135, name: "Jolteon", nameDe: "Blitza" },
  { id: 136, name: "Flareon", nameDe: "Flamara" },
  { id: 137, name: "Porygon", nameDe: "Porygon" },
  { id: 138, name: "Omanyte", nameDe: "Amonitas" },
  { id: 139, name: "Omastar", nameDe: "Amoroso" },
  { id: 140, name: "Kabuto", nameDe: "Kabuto" },
  { id: 141, name: "Kabutops", nameDe: "Kabutops" },
  { id: 142, name: "Aerodactyl", nameDe: "Aerodactyl" },
  { id: 143, name: "Snorlax", nameDe: "Relaxo" },
  { id: 144, name: "Articuno", nameDe: "Arktos" },
  { id: 145, name: "Zapdos", nameDe: "Zapdos" },
  { id: 146, name: "Moltres", nameDe: "Lavados" },
  { id: 147, name: "Dratini", nameDe: "Dratini" },
  { id: 148, name: "Dragonair", nameDe: "Dragonir" },
  { id: 149, name: "Dragonite", nameDe: "Dragoran" },
  { id: 150, name: "Mewtwo", nameDe: "Mewtu" },
  { id: 151, name: "Mew", nameDe: "Mew" },
  { id: 152, name: "Chikorita", nameDe: "Endivie" },
  { id: 153, name: "Bayleef", nameDe: "Lorblatt" },
  { id: 154, name: "Meganium", nameDe: "Meganie" },
  { id: 155, name: "Cyndaquil", nameDe: "Feurigel" },
  { id: 156, name: "Quilava", nameDe: "Igelavar" },
  { id: 157, name: "Typhlosion", nameDe: "Tornupto" },
  { id: 158, name: "Totodile", nameDe: "Karnimani" },
  { id: 159, name: "Croconaw", nameDe: "Tyracroc" },
  { id: 160, name: "Feraligatr", nameDe: "Impergator" },
  { id: 161, name: "Sentret", nameDe: "Wiesor" },
  { id: 162, name: "Furret", nameDe: "Wiesenior" },
  { id: 163, name: "Hoothoot", nameDe: "Hoothoot" },
  { id: 164, name: "Noctowl", nameDe: "Noctuh" },
  { id: 165, name: "Ledyba", nameDe: "Ledyba" },
  { id: 166, name: "Ledian", nameDe: "Ledian" },
  { id: 167, name: "Spinarak", nameDe: "Webarak" },
  { id: 168, name: "Ariados", nameDe: "Ariados" },
  { id: 169, name: "Crobat", nameDe: "Iksbat" },
  { id: 170, name: "Chinchou", nameDe: "Lampi" },
  { id: 171, name: "Lanturn", nameDe: "Lanturn" },
  { id: 172, name: "Pichu", nameDe: "Pichu" },
  { id: 173, name: "Cleffa", nameDe: "Pii" },
  { id: 174, name: "Igglybuff", nameDe: "Fluffeluff" },
  { id: 175, name: "Togepi", nameDe: "Togepi" },
  { id: 176, name: "Togetic", nameDe: "Togetic" },
  { id: 177, name: "Natu", nameDe: "Natu" },
  { id: 178, name: "Xatu", nameDe: "Xatu" },
  { id: 179, name: "Mareep", nameDe: "Voltilamm" },
  { id: 180, name: "Flaaffy", nameDe: "Waaty" },
  { id: 181, name: "Ampharos", nameDe: "Ampharos" },
  { id: 182, name: "Bellossom", nameDe: "Blubella" },
  { id: 183, name: "Marill", nameDe: "Marill" },
  { id: 184, name: "Azumarill", nameDe: "Azumarill" },
  { id: 185, name: "Sudowoodo", nameDe: "Mogelbaum" },
  { id: 186, name: "Politoed", nameDe: "Quaxo" },
  { id: 187, name: "Hoppip", nameDe: "Hoppspross" },
  { id: 188, name: "Skiploom", nameDe: "Hubelupf" },
  { id: 189, name: "Jumpluff", nameDe: "Papungha" },
  { id: 190, name: "Aipom", nameDe: "Griffel" },
  { id: 191, name: "Sunkern", nameDe: "Sonnkern" },
  { id: 192, name: "Sunflora", nameDe: "Sonnflora" },
  { id: 193, name: "Yanma", nameDe: "Yanma" },
  { id: 194, name: "Wooper", nameDe: "Felino" },
  { id: 195, name: "Quagsire", nameDe: "Morlord" },
  { id: 196, name: "Espeon", nameDe: "Psiana" },
  { id: 197, name: "Umbreon", nameDe: "Nachtara" },
  { id: 198, name: "Murkrow", nameDe: "Kramurx" },
  { id: 199, name: "Slowking", nameDe: "Laschoking" },
  { id: 200, name: "Misdreavus", nameDe: "Traunfugil" },
  { id: 201, name: "Unown", nameDe: "Icognito" },
  { id: 202, name: "Wobbuffet", nameDe: "Woingenau" },
  { id: 203, name: "Girafarig", nameDe: "Girafarig" },
  { id: 204, name: "Pineco", nameDe: "Tannza" },
  { id: 205, name: "Forretress", nameDe: "Forstellka" },
  { id: 206, name: "Dunsparce", nameDe: "Dummisel" },
  { id: 207, name: "Gligar", nameDe: "Skorgla" },
  { id: 208, name: "Steelix", nameDe: "Stahlos" },
  { id: 209, name: "Snubbull", nameDe: "Snubbull" },
  { id: 210, name: "Granbull", nameDe: "Granbull" },
  { id: 211, name: "Qwilfish", nameDe: "Baldorfish" },
  { id: 212, name: "Scizor", nameDe: "Scherox" },
  { id: 213, name: "Shuckle", nameDe: "Pottrott" },
  { id: 214, name: "Heracross", nameDe: "Skaraborn" },
  { id: 215, name: "Sneasel", nameDe: "Sniebel" },
  { id: 216, name: "Teddiursa", nameDe: "Teddiursa" },
  { id: 217, name: "Ursaring", nameDe: "Ursaring" },
  { id: 218, name: "Slugma", nameDe: "Schneckmag" },
  { id: 219, name: "Magcargo", nameDe: "Magcargo" },
  { id: 220, name: "Swinub", nameDe: "Quiekel" },
  { id: 221, name: "Piloswine", nameDe: "Keifel" },
  { id: 222, name: "Corsola", nameDe: "Corasonn" },
  { id: 223, name: "Remoraid", nameDe: "Remoraid" },
  { id: 224, name: "Octillery", nameDe: "Octillery" },
  { id: 225, name: "Delibird", nameDe: "Botogel" },
  { id: 226, name: "Mantine", nameDe: "Mantax" },
  { id: 227, name: "Skarmory", nameDe: "Panzaeron" },
  { id: 228, name: "Houndour", nameDe: "Hunduster" },
  { id: 229, name: "Houndoom", nameDe: "Hundemon" },
  { id: 230, name: "Kingdra", nameDe: "Seedraking" },
  { id: 231, name: "Phanpy", nameDe: "Phanpy" },
  { id: 232, name: "Donphan", nameDe: "Donphan" },
  { id: 233, name: "Porygon2", nameDe: "Porygon2" },
  { id: 234, name: "Stantler", nameDe: "Damhirplex" },
  { id: 235, name: "Smeargle", nameDe: "Farbeagle" },
  { id: 236, name: "Tyrogue", nameDe: "Rabauz" },
  { id: 237, name: "Hitmontop", nameDe: "Kapoera" },
  { id: 238, name: "Smoochum", nameDe: "Kussilla" },
  { id: 239, name: "Elekid", nameDe: "Elekid" },
  { id: 240, name: "Magby", nameDe: "Magby" },
  { id: 241, name: "Miltank", nameDe: "Miltank" },
  { id: 242, name: "Blissey", nameDe: "Heiteira" },
  { id: 243, name: "Raikou", nameDe: "Raikou" },
  { id: 244, name: "Entei", nameDe: "Entei" },
  { id: 245, name: "Suicune", nameDe: "Suicune" },
  { id: 246, name: "Larvitar", nameDe: "Larvitar" },
  { id: 247, name: "Pupitar", nameDe: "Pupitar" },
  { id: 248, name: "Tyranitar", nameDe: "Despotar" },
  { id: 249, name: "Lugia", nameDe: "Lugia" },
  { id: 250, name: "Ho Oh", nameDe: "Ho-Oh" },
  { id: 251, name: "Celebi", nameDe: "Celebi" },
  { id: 252, name: "Treecko", nameDe: "Geckarbor" },
  { id: 253, name: "Grovyle", nameDe: "Reptain" },
  { id: 254, name: "Sceptile", nameDe: "Gewaldro" },
  { id: 255, name: "Torchic", nameDe: "Flemmli" },
  { id: 256, name: "Combusken", nameDe: "Jungglut" },
  { id: 257, name: "Blaziken", nameDe: "Lohgock" },
  { id: 258, name: "Mudkip", nameDe: "Hydropi" },
  { id: 259, name: "Marshtomp", nameDe: "Moorabbel" },
  { id: 260, name: "Swampert", nameDe: "Sumpex" },
  { id: 261, name: "Poochyena", nameDe: "Fiffyen" },
  { id: 262, name: "Mightyena", nameDe: "Magnayen" },
  { id: 263, name: "Zigzagoon", nameDe: "Zigzachs" },
  { id: 264, name: "Linoone", nameDe: "Geradaks" },
  { id: 265, name: "Wurmple", nameDe: "Waumpel" },
  { id: 266, name: "Silcoon", nameDe: "Schaloko" },
  { id: 267, name: "Beautifly", nameDe: "Papinella" },
  { id: 268, name: "Cascoon", nameDe: "Panekon" },
  { id: 269, name: "Dustox", nameDe: "Pudox" },
  { id: 270, name: "Lotad", nameDe: "Loturzel" },
  { id: 271, name: "Lombre", nameDe: "Lombrero" },
  { id: 272, name: "Ludicolo", nameDe: "Kappalores" },
  { id: 273, name: "Seedot", nameDe: "Samurzel" },
  { id: 274, name: "Nuzleaf", nameDe: "Blanas" },
  { id: 275, name: "Shiftry", nameDe: "Tengulist" },
  { id: 276, name: "Taillow", nameDe: "Schwalbini" },
  { id: 277, name: "Swellow", nameDe: "Schwalboss" },
  { id: 278, name: "Wingull", nameDe: "Wingull" },
  { id: 279, name: "Pelipper", nameDe: "Pelipper" },
  { id: 280, name: "Ralts", nameDe: "Trasla" },
  { id: 281, name: "Kirlia", nameDe: "Kirlia" },
  { id: 282, name: "Gardevoir", nameDe: "Guardevoir" },
  { id: 283, name: "Surskit", nameDe: "Gehweiher" },
  { id: 284, name: "Masquerain", nameDe: "Maskeregen" },
  { id: 285, name: "Shroomish", nameDe: "Knilz" },
  { id: 286, name: "Breloom", nameDe: "Kapilz" },
  { id: 287, name: "Slakoth", nameDe: "Bummelz" },
  { id: 288, name: "Vigoroth", nameDe: "Muntier" },
  { id: 289, name: "Slaking", nameDe: "Letarking" },
  { id: 290, name: "Nincada", nameDe: "Nincada" },
  { id: 291, name: "Ninjask", nameDe: "Ninjask" },
  { id: 292, name: "Shedinja", nameDe: "Ninjatom" },
  { id: 293, name: "Whismur", nameDe: "Flurmel" },
  { id: 294, name: "Loudred", nameDe: "Krakeelo" },
  { id: 295, name: "Exploud", nameDe: "Krawumms" },
  { id: 296, name: "Makuhita", nameDe: "Makuhita" },
  { id: 297, name: "Hariyama", nameDe: "Hariyama" },
  { id: 298, name: "Azurill", nameDe: "Azurill" },
  { id: 299, name: "Nosepass", nameDe: "Nasgnet" },
  { id: 300, name: "Skitty", nameDe: "Eneco" },
  { id: 301, name: "Delcatty", nameDe: "Enekoro" },
  { id: 302, name: "Sableye", nameDe: "Zobiris" },
  { id: 303, name: "Mawile", nameDe: "Flunkifer" },
  { id: 304, name: "Aron", nameDe: "Stollunior" },
  { id: 305, name: "Lairon", nameDe: "Stollrak" },
  { id: 306, name: "Aggron", nameDe: "Stolloss" },
  { id: 307, name: "Meditite", nameDe: "Meditie" },
  { id: 308, name: "Medicham", nameDe: "Meditalis" },
  { id: 309, name: "Electrike", nameDe: "Frizelbliz" },
  { id: 310, name: "Manectric", nameDe: "Voltenso" },
  { id: 311, name: "Plusle", nameDe: "Plusle" },
  { id: 312, name: "Minun", nameDe: "Minun" },
  { id: 313, name: "Volbeat", nameDe: "Volbeat" },
  { id: 314, name: "Illumise", nameDe: "Illumise" },
  { id: 315, name: "Roselia", nameDe: "Roselia" },
  { id: 316, name: "Gulpin", nameDe: "Schluppuck" },
  { id: 317, name: "Swalot", nameDe: "Schlukwech" },
  { id: 318, name: "Carvanha", nameDe: "Kanivanha" },
  { id: 319, name: "Sharpedo", nameDe: "Tohaido" },
  { id: 320, name: "Wailmer", nameDe: "Wailmer" },
  { id: 321, name: "Wailord", nameDe: "Wailord" },
  { id: 322, name: "Numel", nameDe: "Camaub" },
  { id: 323, name: "Camerupt", nameDe: "Camerupt" },
  { id: 324, name: "Torkoal", nameDe: "Qurtel" },
  { id: 325, name: "Spoink", nameDe: "Spoink" },
  { id: 326, name: "Grumpig", nameDe: "Groink" },
  { id: 327, name: "Spinda", nameDe: "Pandir" },
  { id: 328, name: "Trapinch", nameDe: "Knacklion" },
  { id: 329, name: "Vibrava", nameDe: "Vibrava" },
  { id: 330, name: "Flygon", nameDe: "Libelldra" },
  { id: 331, name: "Cacnea", nameDe: "Tuska" },
  { id: 332, name: "Cacturne", nameDe: "Noktuska" },
  { id: 333, name: "Swablu", nameDe: "Wablu" },
  { id: 334, name: "Altaria", nameDe: "Altaria" },
  { id: 335, name: "Zangoose", nameDe: "Sengo" },
  { id: 336, name: "Seviper", nameDe: "Vipitis" },
  { id: 337, name: "Lunatone", nameDe: "Lunastein" },
  { id: 338, name: "Solrock", nameDe: "Sonnfel" },
  { id: 339, name: "Barboach", nameDe: "Schmerbe" },
  { id: 340, name: "Whiscash", nameDe: "Welsar" },
  { id: 341, name: "Corphish", nameDe: "Krebscorps" },
  { id: 342, name: "Crawdaunt", nameDe: "Krebutack" },
  { id: 343, name: "Baltoy", nameDe: "Puppance" },
  { id: 344, name: "Claydol", nameDe: "Lepumentas" },
  { id: 345, name: "Lileep", nameDe: "Liliep" },
  { id: 346, name: "Cradily", nameDe: "Wielie" },
  { id: 347, name: "Anorith", nameDe: "Anorith" },
  { id: 348, name: "Armaldo", nameDe: "Armaldo" },
  { id: 349, name: "Feebas", nameDe: "Barschwa" },
  { id: 350, name: "Milotic", nameDe: "Milotic" },
  { id: 351, name: "Castform", nameDe: "Formeo" },
  { id: 352, name: "Kecleon", nameDe: "Kecleon" },
  { id: 353, name: "Shuppet", nameDe: "Shuppet" },
  { id: 354, name: "Banette", nameDe: "Banette" },
  { id: 355, name: "Duskull", nameDe: "Zwirrlicht" },
  { id: 356, name: "Dusclops", nameDe: "Zwirrklop" },
  { id: 357, name: "Tropius", nameDe: "Tropius" },
  { id: 358, name: "Chimecho", nameDe: "Palimpalim" },
  { id: 359, name: "Absol", nameDe: "Absol" },
  { id: 360, name: "Wynaut", nameDe: "Isso" },
  { id: 361, name: "Snorunt", nameDe: "Schneppke" },
  { id: 362, name: "Glalie", nameDe: "Firnontor" },
  { id: 363, name: "Spheal", nameDe: "Seemops" },
  { id: 364, name: "Sealeo", nameDe: "Seejong" },
  { id: 365, name: "Walrein", nameDe: "Walraisa" },
  { id: 366, name: "Clamperl", nameDe: "Perlu" },
  { id: 367, name: "Huntail", nameDe: "Aalabyss" },
  { id: 368, name: "Gorebyss", nameDe: "Saganabyss" },
  { id: 369, name: "Relicanth", nameDe: "Relicanth" },
  { id: 370, name: "Luvdisc", nameDe: "Liebiskus" },
  { id: 371, name: "Bagon", nameDe: "Kindwurm" },
  { id: 372, name: "Shelgon", nameDe: "Draschel" },
  { id: 373, name: "Salamence", nameDe: "Brutalanda" },
  { id: 374, name: "Beldum", nameDe: "Tanhel" },
  { id: 375, name: "Metang", nameDe: "Metang" },
  { id: 376, name: "Metagross", nameDe: "Metagross" },
  { id: 377, name: "Regirock", nameDe: "Regirock" },
  { id: 378, name: "Regice", nameDe: "Regice" },
  { id: 379, name: "Registeel", nameDe: "Registeel" },
  { id: 380, name: "Latias", nameDe: "Latias" },
  { id: 381, name: "Latios", nameDe: "Latios" },
  { id: 382, name: "Kyogre", nameDe: "Kyogre" },
  { id: 383, name: "Groudon", nameDe: "Groudon" },
  { id: 384, name: "Rayquaza", nameDe: "Rayquaza" },
  { id: 385, name: "Jirachi", nameDe: "Jirachi" },
  { id: 386, name: "Deoxys", nameDe: "Deoxys" },
  { id: 387, name: "Turtwig", nameDe: "Chelast" },
  { id: 388, name: "Grotle", nameDe: "Chelcarain" },
  { id: 389, name: "Torterra", nameDe: "Chelterrar" },
  { id: 390, name: "Chimchar", nameDe: "Panflam" },
  { id: 391, name: "Monferno", nameDe: "Panpyro" },
  { id: 392, name: "Infernape", nameDe: "Panferno" },
  { id: 393, name: "Piplup", nameDe: "Plinfa" },
  { id: 394, name: "Prinplup", nameDe: "Pliprin" },
  { id: 395, name: "Empoleon", nameDe: "Impoleon" },
  { id: 396, name: "Starly", nameDe: "Staralili" },
  { id: 397, name: "Staravia", nameDe: "Staravia" },
  { id: 398, name: "Staraptor", nameDe: "Staraptor" },
  { id: 399, name: "Bidoof", nameDe: "Bidiza" },
  { id: 400, name: "Bibarel", nameDe: "Bidifas" },
  { id: 401, name: "Kricketot", nameDe: "Zirpurze" },
  { id: 402, name: "Kricketune", nameDe: "Zirpeise" },
  { id: 403, name: "Shinx", nameDe: "Sheinux" },
  { id: 404, name: "Luxio", nameDe: "Luxio" },
  { id: 405, name: "Luxray", nameDe: "Luxtra" },
  { id: 406, name: "Budew", nameDe: "Knospi" },
  { id: 407, name: "Roserade", nameDe: "Roserade" },
  { id: 408, name: "Cranidos", nameDe: "Koknodon" },
  { id: 409, name: "Rampardos", nameDe: "Rameidon" },
  { id: 410, name: "Shieldon", nameDe: "Schilterus" },
  { id: 411, name: "Bastiodon", nameDe: "Bollterus" },
  { id: 412, name: "Burmy", nameDe: "Burmy" },
  { id: 413, name: "Wormadam", nameDe: "Burmadame" },
  { id: 414, name: "Mothim", nameDe: "Moterpel" },
  { id: 415, name: "Combee", nameDe: "Wadribie" },
  { id: 416, name: "Vespiquen", nameDe: "Honweisel" },
  { id: 417, name: "Pachirisu", nameDe: "Pachirisu" },
  { id: 418, name: "Buizel", nameDe: "Bamelin" },
  { id: 419, name: "Floatzel", nameDe: "Bojelin" },
  { id: 420, name: "Cherubi", nameDe: "Kikugi" },
  { id: 421, name: "Cherrim", nameDe: "Kinoso" },
  { id: 422, name: "Shellos", nameDe: "Schalellos" },
  { id: 423, name: "Gastrodon", nameDe: "Gastrodon" },
  { id: 424, name: "Ambipom", nameDe: "Ambidiffel" },
  { id: 425, name: "Drifloon", nameDe: "Driftlon" },
  { id: 426, name: "Drifblim", nameDe: "Drifzepeli" },
  { id: 427, name: "Buneary", nameDe: "Haspiror" },
  { id: 428, name: "Lopunny", nameDe: "Schlapor" },
  { id: 429, name: "Mismagius", nameDe: "Traunmagil" },
  { id: 430, name: "Honchkrow", nameDe: "Kramshef" },
  { id: 431, name: "Glameow", nameDe: "Charmian" },
  { id: 432, name: "Purugly", nameDe: "Shnurgarst" },
  { id: 433, name: "Chingling", nameDe: "Klingplim" },
  { id: 434, name: "Stunky", nameDe: "Skunkapuh" },
  { id: 435, name: "Skuntank", nameDe: "Skuntank" },
  { id: 436, name: "Bronzor", nameDe: "Bronzel" },
  { id: 437, name: "Bronzong", nameDe: "Bronzong" },
  { id: 438, name: "Bonsly", nameDe: "Mobai" },
  { id: 439, name: "Mime Jr", nameDe: "Pantimimi" },
  { id: 440, name: "Happiny", nameDe: "Wonneira" },
  { id: 441, name: "Chatot", nameDe: "Plaudagei" },
  { id: 442, name: "Spiritomb", nameDe: "Kryppuk" },
  { id: 443, name: "Gible", nameDe: "Kaumalat" },
  { id: 444, name: "Gabite", nameDe: "Knarksel" },
  { id: 445, name: "Garchomp", nameDe: "Knakrack" },
  { id: 446, name: "Munchlax", nameDe: "Mampfaxo" },
  { id: 447, name: "Riolu", nameDe: "Riolu" },
  { id: 448, name: "Lucario", nameDe: "Lucario" },
  { id: 449, name: "Hippopotas", nameDe: "Hippopotas" },
  { id: 450, name: "Hippowdon", nameDe: "Hippoterus" },
  { id: 451, name: "Skorupi", nameDe: "Pionskora" },
  { id: 452, name: "Drapion", nameDe: "Piondragi" },
  { id: 453, name: "Croagunk", nameDe: "Glibunkel" },
  { id: 454, name: "Toxicroak", nameDe: "Toxiquak" },
  { id: 455, name: "Carnivine", nameDe: "Venuflibis" },
  { id: 456, name: "Finneon", nameDe: "Finneon" },
  { id: 457, name: "Lumineon", nameDe: "Lumineon" },
  { id: 458, name: "Mantyke", nameDe: "Mantirps" },
  { id: 459, name: "Snover", nameDe: "Shnebedeck" },
  { id: 460, name: "Abomasnow", nameDe: "Rexblisar" },
  { id: 461, name: "Weavile", nameDe: "Snibunna" },
  { id: 462, name: "Magnezone", nameDe: "Magnezone" },
  { id: 463, name: "Lickilicky", nameDe: "Schlurplek" },
  { id: 464, name: "Rhyperior", nameDe: "Rihornior" },
  { id: 465, name: "Tangrowth", nameDe: "Tangoloss" },
  { id: 466, name: "Electivire", nameDe: "Elevoltek" },
  { id: 467, name: "Magmortar", nameDe: "Magbrant" },
  { id: 468, name: "Togekiss", nameDe: "Togekiss" },
  { id: 469, name: "Yanmega", nameDe: "Yanmega" },
  { id: 470, name: "Leafeon", nameDe: "Folipurba" },
  { id: 471, name: "Glaceon", nameDe: "Glaziola" },
  { id: 472, name: "Gliscor", nameDe: "Skorgro" },
  { id: 473, name: "Mamoswine", nameDe: "Mamutel" },
  { id: 474, name: "Porygon Z", nameDe: "Porygon-Z" },
  { id: 475, name: "Gallade", nameDe: "Galagladi" },
  { id: 476, name: "Probopass", nameDe: "Voluminas" },
  { id: 477, name: "Dusknoir", nameDe: "Zwirrfinst" },
  { id: 478, name: "Froslass", nameDe: "Frosdedje" },
  { id: 479, name: "Rotom", nameDe: "Rotom" },
  { id: 480, name: "Uxie", nameDe: "Selfe" },
  { id: 481, name: "Mesprit", nameDe: "Vesprit" },
  { id: 482, name: "Azelf", nameDe: "Tobutz" },
  { id: 483, name: "Dialga", nameDe: "Dialga" },
  { id: 484, name: "Palkia", nameDe: "Palkia" },
  { id: 485, name: "Heatran", nameDe: "Heatran" },
  { id: 486, name: "Regigigas", nameDe: "Regigigas" },
  { id: 487, name: "Giratina", nameDe: "Giratina" },
  { id: 488, name: "Cresselia", nameDe: "Cresselia" },
  { id: 489, name: "Phione", nameDe: "Phione" },
  { id: 490, name: "Manaphy", nameDe: "Manaphy" },
  { id: 491, name: "Darkrai", nameDe: "Darkrai" },
  { id: 492, name: "Shaymin", nameDe: "Shaymin" },
  { id: 493, name: "Arceus", nameDe: "Arceus" },
];

const BY_ID = new Map(POKEDEX.map((p) => [p.id, p]));
const BY_NAME = new Map(POKEDEX.map((p) => [p.name.toLowerCase(), p]));
const BY_NAME_DE = new Map(POKEDEX.map((p) => [p.nameDe.toLowerCase(), p]));

export function getPokemonById(id: number): PokedexEntry | undefined {
  return BY_ID.get(id);
}

/** Looks up a Pokemon by its English *or* German name (case-insensitive, exact match). */
export function getPokemonByName(name: string): PokedexEntry | undefined {
  const key = name.trim().toLowerCase();
  return BY_NAME.get(key) ?? BY_NAME_DE.get(key);
}

export function isValidSpeciesId(id: number): boolean {
  return BY_ID.has(id);
}

/**
 * Case-insensitive substring search across both the English and German
 * names. Shared by any UI (e.g. the desktop picker) that needs bilingual
 * Pokemon search instead of re-implementing the matching logic per component.
 */
export function searchPokedex(query: string): PokedexEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return POKEDEX;
  return POKEDEX.filter((p) => p.name.toLowerCase().includes(q) || p.nameDe.toLowerCase().includes(q));
}

/**
 * Official artwork sprite URL served from the community PokeAPI sprites CDN.
 * No API key or extra API round trip is required beyond loading the image itself.
 */
export function spriteUrlFor(speciesId: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${speciesId}.png`;
}

/**
 * Localized display name for a species, in the given tooltip language.
 * Falls back to `#<id>` for an unknown species so callers never need to
 * hardcode a fallback string themselves.
 */
export function getPokemonDisplayName(speciesId: number, language: TooltipLanguage = 'en'): string {
  const entry = getPokemonById(speciesId);
  if (!entry) return `#${speciesId}`;
  return language === 'de' ? entry.nameDe : entry.name;
}
